<?php
include("top.html");
?>

<h1>Enter Donors</h1>
<p id="save-status" aria-live="polite">Not saved yet</p>

<div id="dup-box" class="dup-box" role="alert" hidden>
    <p id="dup-msg"></p>
    <ul id="dup-list"></ul>
    <button type="button" id="dup-yes">Add anyway</button>
    <button type="button" id="dup-no">Cancel</button>
</div>

<form id="donor-form">
    <!-- Empty = a brand new donor (insert). Filled in after the first save (update).
         The donor number itself is generated by the database (starts at 5000). -->
    <input type="hidden" id="donor_id" value="">

    <label for="name">Donor Name</label><br>
    <input type="text" id="name" name="name" maxlength="100" required autofocus><br><br>

    <label for="address">Address</label><br>
    <input type="text" id="address" name="address" maxlength="200"><br><br>

    <label for="phone">Phone Number</label><br>
    <input type="text" id="phone" name="phone" maxlength="20"><br><br>

    <!-- Clears the form so the next donor is a new row, not an edit of this one. -->
    <button type="button" id="new-donor">Start New Donor</button>
</form>

<script src="js/donors.js"></script>

<?php include("bottom.html"); ?>
